version: '2.1'

services:
  openmrs-referenceapplication-mysql:
    restart: "always"
    image: mysql:5.6
    command: "mysqld --character-set-server=utf8 --collation-server=utf8_general_ci"
    environment:
      MYSQL_DATABASE: ${MYSQL_DB:-openmrs}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-Admin123}
      MYSQL_USER: ${MYSQL_USER:-openmrs}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-Admin123}
    healthcheck:
      test: "exit 0"
    volumes:
      - ./dbdump:/docker-entrypoint-initdb.d
      # - openmrs-referenceapplication-mysql-data:/var/lib/mysql  # uncomment to keep database between docker runs

  openmrs-referenceapplication:
    restart: "always"
    image: openmrs/openmrs-reference-application:${OPENMRS_VERSION:-qa}
    depends_on:
      - openmrs-referenceapplication-mysql
    ports:
      - "8081:8080"
    environment:
      OMRS_CONFIG_MODULE_WEB_ADMIN: "false"
      OMRS_CONFIG_AUTO_UPDATE_DATABASE: "true"
      OMRS_CONFIG_CREATE_TABLES: "false"
      OMRS_CONFIG_CONNECTION_SERVER: openmrs-referenceapplication-mysql
      OMRS_CONFIG_CONNECTION_URL: ${OPENMRS_DB_URL}
      OMRS_CONFIG_CONNECTION_DATABASE: ${MYSQL_DB:-openmrs}
      OMRS_CONFIG_CONNECTION_USERNAME: ${MYSQL_USER:-openmrs}
      OMRS_CONFIG_CONNECTION_PASSWORD: ${MYSQL_PASSWORD:-Admin123}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/openmrs/"]
      timeout: 20s

volumes:
  openmrs-referenceapplication-mysql-data: