version: '3'

services:
  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-keycloak}
      POSTGRES_USER: ${POSTGRES_USER:-keycloak}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
    restart: "always"
  keycloak:
    image: openmrs/openmrs-id-keycloak:latest
    environment:
      - KC_HOSTNAME=${HOSTNAME:-localhost}
      - KC_DB=postgres
      - KC_DB_URL_DATABASE=${POSTGRES_DB:-keycloak}
      - KC_DB_URL_HOST=postgres
      - KC_DB_URL_PORT=5432
      - KC_DB_USERNAME=${POSTGRES_USER:-keycloak}
      - KC_DB_PASSWORD=${POSTGRES_PASSWORD:-password}
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN:-admin}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD:-password}
      - KC_PROXY:${KC_PROXY:-none}
      - PROXY_ADDRESS_FORWARDING=${PROXY_ADDRESS_FORWARDING:-false}
    restart: "always"
    ports:
      - "8443:8443"
    depends_on:
      - postgres
  postfix:
    image: openmrs/openmrs-id-postfix:latest
    ports:
      - "25:25"
volumes:
  postgres_data:
    driver: local
  postfix_data:
    driver: local
